<a href="https://colab.research.google.com/github/alkarps/GB.Machine-learning-in-business/blob/hw01/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<b> В задании нужно загрузить датасет с данными оттока и ответить на несколько вопросов (написать код). При этом сам датасет уже есть и его необязательно качать с репозитория</b>

Цель задания: проверить базовые навыки работы студентов с Pandas, умение проводить такой же базовый EDA (exploratory data analysis), делать feature engineering и обучать и валидировать модель.

Список столбцов с типами данных в датасете:

- customerID           object
- gender               object
- SeniorCitizen         int64
- Partner              object
- Dependents           object
- tenure                int64
- PhoneService         object
- MultipleLines        object
- InternetService      object
- OnlineSecurity       object
- OnlineBackup         object
- DeviceProtection     object
- TechSupport          object
- StreamingTV          object
- StreamingMovies      object
- Contract             object
- PaperlessBilling     object
- PaymentMethod        object
- MonthlyCharges      float64
- TotalCharges         object
- Churn                object

Данные лежат на google диске по [ссылке](https://drive.google.com/file/d/1g8lsZO25O2SxuCrIYVSDV3eLqmfC-TCZ/view?usp=sharing).

In [1]:
!wget 'https://drive.google.com/uc?export=download&id=1g8lsZO25O2SxuCrIYVSDV3eLqmfC-TCZ' -O WA_Fn-UseC_-Telco-Customer-Churn.csv

--2023-05-01 16:21:43--  https://drive.google.com/uc?export=download&id=1g8lsZO25O2SxuCrIYVSDV3eLqmfC-TCZ
Resolving drive.google.com (drive.google.com)... 173.194.212.113, 173.194.212.100, 173.194.212.101, ...
Connecting to drive.google.com (drive.google.com)|173.194.212.113|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://doc-08-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/uot46vh658a4k4rln0cucilosrf2kp2r/1682958075000/14904333240138417226/*/1g8lsZO25O2SxuCrIYVSDV3eLqmfC-TCZ?e=download&uuid=8a9d4f85-a6b6-4911-904b-761d95e6035e [following]
--2023-05-01 16:21:44--  https://doc-08-c0-docs.googleusercontent.com/docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/uot46vh658a4k4rln0cucilosrf2kp2r/1682958075000/14904333240138417226/*/1g8lsZO25O2SxuCrIYVSDV3eLqmfC-TCZ?e=download&uuid=8a9d4f85-a6b6-4911-904b-761d95e6035e
Resolving doc-08-c0-docs.googleusercontent.com (doc-08-c0-docs.googleusercontent.com)... 172.217.193.132, 

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("./WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head(3)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   
2  3668-QPYBK    Male              0      No         No       2          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   
2                No             DSL            Yes  ...               No   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   
2          No          No              No  Month-to-month              Yes   

      PaymentMethod MonthlyCharges  TotalCharges Churn  
0  Electronic check          29.85         29.85    No  
1      Mailed check          56.95        1889.5    No  
2      Mailed check          53.85        108.15   Yes  

[3 rows x 21 columns]

##### 1. Какое соотношение мужчин и женщин в представленном наборе данных?

In [3]:
df['gender'].value_counts()

Male      3555
Female    3488
Name: gender, dtype: int64

##### 2. Какое количество уникальных значений у поля InternetService?

In [4]:
df['InternetService'].unique()

array(['DSL', 'Fiber optic', 'No'], dtype=object)

##### 3. Выведите статистики по полю TotalCharges (median, mean, std).

In [5]:
df['TotalCharges'].describe()

count     7043
unique    6531
top           
freq        11
Name: TotalCharges, dtype: object

В чем странность того, что вы получили? (подсказка: смотреть нужно на тип данных)

##### 4. Сделайте замену значений поля PhoneService  на числовые (Yes->1, No->0)

In [6]:
df['PhoneService'].unique()

array(['No', 'Yes'], dtype=object)

In [7]:
df['PhoneService']=df['PhoneService'].replace(['No', 'Yes'], [0,1])

In [8]:
df['PhoneService'].unique()

array([0, 1])

##### 5. Сделайте замену пробелов в поле TotalCharges на np.nan и приведите поле к типу данных float32. Затем заполните оставшиеся пропуски значением 0 с помощью метода fillna у столбца. Снова выведите статистики и сравните с тем, что вы видели в вопросе 3

In [9]:
df['TotalCharges'] = df['TotalCharges'].replace(r'\s+', np.nan, regex=True).astype(np.float64).fillna(0)

In [10]:
df['TotalCharges'].describe()

count    7043.000000
mean     2279.734304
std      2266.794470
min         0.000000
25%       398.550000
50%      1394.550000
75%      3786.600000
max      8684.800000
Name: TotalCharges, dtype: float64

##### 6. Сделайте замену значений поля Churn на числовые (Yes -> 1, No - 0)

In [11]:
df['Churn'].unique()

array(['No', 'Yes'], dtype=object)

In [12]:
df['Churn']=df['Churn'].replace(['No', 'Yes'], [0,1])

In [13]:
df['Churn'].unique()

array([0, 1])

##### 7. Сделайте замену значений полей StreamingMovies, StreamingTV, TechSupport  на числовые (Yes -> 1, No -> 0, No internet service->0)

In [14]:
df['StreamingMovies'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [15]:
df['StreamingTV'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [16]:
df['TechSupport'].unique()

array(['No', 'Yes', 'No internet service'], dtype=object)

In [17]:
df['StreamingMovies']= df['StreamingMovies'].map({'Yes':1}).fillna(0).astype(np.int8)

In [18]:
df['StreamingTV']=df['StreamingTV'].map({'Yes':1}).fillna(0).astype(np.int8)

In [19]:
df['TechSupport']=df['TechSupport'].map({'Yes':1}).fillna(0).astype(np.int8)

In [20]:
df['StreamingMovies'].unique()

array([0, 1], dtype=int8)

In [21]:
df['StreamingTV'].unique()

array([0, 1], dtype=int8)

In [22]:
df['TechSupport'].unique()

array([0, 1], dtype=int8)

##### 8. Заполните пропуски в поле PhoneService значением 0

In [23]:
df['PhoneService']=df['PhoneService'].fillna(0)

##### 8. Для нашего датасета оставьте только указанный ниже список полей, удалив все другие и выведите верхние 3 строки

In [24]:
columns = ['gender', 'tenure', 'PhoneService', 'TotalCharges', 'StreamingMovies', 'StreamingTV', 'TechSupport', 'Churn']
df = df[df.columns.intersection(columns)]
df.head(3)

gender  tenure  PhoneService  TechSupport  StreamingTV  StreamingMovies  \
0  Female       1             0            0            0                0   
1    Male      34             1            0            0                0   
2    Male       2             1            0            0                0   

   TotalCharges  Churn  
0         29.85      0  
1       1889.50      0  
2        108.15      1

##### 9. Разделите датасет на тренировочную и тестовую выборку.

In [25]:
features = ['gender', 'tenure', 'PhoneService', 'TotalCharges', 'StreamingMovies', 'StreamingTV', 'TechSupport']
target = 'Churn'

In [26]:
from sklearn.model_selection import train_test_split


y = df.pop(target)
X = df

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
X_train.head(3)

gender  tenure  PhoneService  TechSupport  StreamingTV  StreamingMovies  \
478     Male       5             1            1            1                1   
958     Male      25             1            1            0                1   
5378  Female      58             1            1            1                0   

      TotalCharges  
478         453.40  
958        2028.80  
5378       4415.75

In [27]:
y_train.head(3)

478     1
958     0
5378    0
Name: Churn, dtype: int64

In [28]:
X_test.head(3)

gender  tenure  PhoneService  TechSupport  StreamingTV  StreamingMovies  \
6277   Male       2             1            0            0                0   
4324   Male      40             1            0            0                1   
28     Male      72             1            1            1                1   

      TotalCharges  
6277         33.20  
4324       2731.00  
28         6369.45

In [29]:
y_test.head(3)

6277    1
4324    0
28      0
Name: Churn, dtype: int64

##### 10. соберите pipeline для поля gender (нужно разобраться и изучить https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html ) из классов ColumnSelector и OHEEncoder, которые уже написаны ниже заранее

In [30]:
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline

class ColumnSelector(BaseEstimator, TransformerMixin):
    """
    Transformer to select a single column from the data frame to perform additional transformations on
    """
    def __init__(self, key):
        self.key = key

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[self.key]
    
class NumberSelector(BaseEstimator, TransformerMixin):
    """
    Transformer to select a single column from the data frame to perform additional transformations on
    Use on numeric columns in the data
    """
    def __init__(self, key):
        self.key = key

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X[[self.key]]
    
class OHEEncoder(BaseEstimator, TransformerMixin):
    def __init__(self, key):
        self.key = key
        self.columns = []

    def fit(self, X, y=None):
        self.columns = [col for col in pd.get_dummies(X, prefix=self.key).columns]
        return self

    def transform(self, X):
        X = pd.get_dummies(X, prefix=self.key)
        test_columns = [col for col in X.columns]
        for col_ in self.columns:
            if col_ not in test_columns:
                X[col_] = 0
        return X[self.columns]

gender = Pipeline([
                ('selector', OHEEncoder(key='gender'))
            ])

##### 11. Вызовите метод fit_transform у пайплайна gender и передайте туда нашу тренировочную выборку (пример по ссылке из документации https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline.fit)

In [31]:
gender.fit_transform(X_train, y_train).head(3)

tenure  PhoneService  TechSupport  StreamingTV  StreamingMovies  \
478        5             1            1            1                1   
958       25             1            1            0                1   
5378      58             1            1            1                0   

      TotalCharges  gender_Female  gender_Male  
478         453.40              0            1  
958        2028.80              0            1  
5378       4415.75              1            0

##### 12. Здесь код писать уже не нужно (все сделано за вас). К полю tenure применяем StandardScaler (нормируем и центрируем). Ссылка - https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
Вопрос - в каких случаях это может быть полезно?

In [32]:
from sklearn.preprocessing import StandardScaler

tenure =  Pipeline([
                ('selector', NumberSelector(key='tenure')),
                ('standard', StandardScaler())
            ])

Полезно, когда данные не находятся в одном масштабе

##### 13. Напишите аналогичный (как для tenure) преобразователь поля TotalCharges

In [33]:
TotalCharges =  Pipeline([
                ('selector', NumberSelector(key='TotalCharges')),
                ('standard', StandardScaler())
            ])


Объединение всех "кубиков" очень легко сделать таким образом

In [34]:
from sklearn.pipeline import FeatureUnion

number_features = Pipeline([
                ('selector', ColumnSelector(key=['PhoneService',
                                                 'StreamingMovies', 'StreamingTV', 
                                                 'TechSupport']))
            ])

In [35]:
feats = FeatureUnion([('tenure', tenure),
                      ('TotalCharges', TotalCharges),
                      ('continuos_features', number_features),
                      ('gender', gender)])
feature_processing = Pipeline([('feats', feats)])

На этом этапе что мы сделали:
1. написали преобразователь поля gender, который делает OHE кодирование
2. написали преобразователь для поля tenure, который нормирует и центрирует его 
3. повторили п. 2 для поля TotalCharges
3. для всех остальных просто взяли признаки как они есть, без изменений

У нас уже готов наш пайплайн, который преобразовывает признаки. Давайте обучим модель поверх него. В качестве модели возьмем RandomForestClassifier

In [36]:
from sklearn.ensemble import RandomForestClassifier

pipeline = Pipeline([
    ('features', feats),
    ('classifier', RandomForestClassifier(random_state=42)),
])

pipeline.fit(X_train, y_train)

Pipeline(steps=[('features',
                 FeatureUnion(transformer_list=[('tenure',
                                                 Pipeline(steps=[('selector',
                                                                  NumberSelector(key='tenure')),
                                                                 ('standard',
                                                                  StandardScaler())])),
                                                ('TotalCharges',
                                                 Pipeline(steps=[('selector',
                                                                  NumberSelector(key='TotalCharges')),
                                                                 ('standard',
                                                                  StandardScaler())])),
                                                ('continuos_features',
                                                 Pipeline(steps=[('selector',
                                                                  ColumnSelector(key=['PhoneService',
                                                                                      'StreamingMovies',
                                                                                      'StreamingTV',
                                                                                      'TechSupport']))])),
                                                ('gender',
                                                 Pipeline(steps=[('selector',
                                                                  OHEEncoder(key='gender'))]))])),
                ('classifier', RandomForestClassifier(random_state=42))])

##### 14. Сделайте прогноз вероятности оттока для X_test с помощью нашего предобученного на предыдущем шаге пайплайна и убедитесь что вам возвращаются вероятности для 2 классов

In [37]:
y_pred = pipeline.predict(X_test)
y_pred

array([0, 0, 0, ..., 1, 1, 0])

##### 15. Посчитайте метрики качества получившейся модели (roc_auc)

In [38]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, y_pred)

0.6585962906504066

### Сохраним наш пайплайн

In [39]:
!pip install dill

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [40]:
import dill
with open("model_RF.dill", "wb") as f:
    dill.dump(pipeline, f)